# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: bba97cd34f9650ff994ea9664946568dc0d256aaa583e430570705210757c6f03990040733a597845994574a2cf2a3f96d822f9d7d8666530c70bbc8debf378f

test:
  secret_key_base: e1c436ec5455abb3d28c15bab880bcb70e2728ea9f9e8e90b5e72f09d2b3c1c50f545cfe976e88bc948a572f2e77eaab7c5254fcf4ab22af56ba80533461ad08

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
